name: Main
on:
  
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: master
      deploy_message:
        description: Deploy Description
jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - uses:  rahulmalewadi/flyway-custom-action@v1.0.0

        with:
          url: ${{secrets.URL}}
          user: ${{secrets.USERNAME}}
          
          password: ${{secrets.PASSWORD}}
          locations: filesystem:./sql
        
        
  

