name: Main
on:
  
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: master
      deploy_message:
        description: Deploy Description
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses:  rahulmalewadi/flyway-custom-action@v1.0.0

        with:
          url: ${{secrets.URL}}
          user: ${{secrets.USERNAME}}
          
          password: ${{secrets.PASSWORD}}
          locations: filesystem:./sql
        
        
  elastic:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: this-will-fail
      - name: elastic-logs
        if: failure()
        uses: masci/elastic-logs@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          cloud-id: ${{ secrets.CLOUD_ID }}
          username: ${{ secrets.ES_USER }}
          password: nSjuaMdIJCQEuV4F8J40F1pl
          job-names: build

