name: Main
on:
  
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: dev
      deploy_message:
        description: Deploy Description
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_PASSWORD: mysql
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses:  rahulmalewadi/flyway-custom-action@v1.0.0
        with:
          url: jdbc:mysql://mydb1.cbidfqjsoekh.us-east-1.rds.amazonaws.com:3306/data1
          user: admin
          password: 123456789
      - run: echo 'testing'
